### ISSUE TITLE
Create a second instance of PostgreSQL 

### ISSUE THREAD

**Issue by f1nal3** [f1nal3/Juniorgram#112]
For testing purposes we need a second instance of PostgreSQL.
Main reason being several tests running in parallel can delete data that is needed by other tests.
To solve this we must create a separate test data or separate DB. 

TBD

AC: TBD

**Comment by f1nal3** [comment]
UPD: We have a second DB(not instance) with a specialised user and right for it. Is there a need for a separate instance? Cause if not, this can be closed. What do you think, @HRenata, @Orange-hanter, @glaush?

**Comment by glaush** [comment]
It's good idea.

**Comment by f1nal3** [comment]
Edited.

**Comment by f1nal3** [comment]
We will have a docker image with database rolled inside of our build to do tests. No need for instances, test database on prod server or something else.

**Comment by f1nal3** [comment]
This is put to "Testing" state until 20.08.2022 to see if the gates work correctly.

**Comment by f1nal3** [comment]
All's fine, closing.
