### ISSUE TITLE
Improve the message processing mechanism on the Client-side. 

### ISSUE THREAD

**Issue by glaush** [f1nal3/Juniorgram#210]
The purpose of this task is to improve the unpacking of messages from the queue, followed by processing in the different callbacks.

At the moment we are unpacking messages from the queue in this way:

![image](https://user-images.githubusercontent.com/56369021/117843285-5ae1ab00-b287-11eb-9ee3-052750ffd1e1.png)

We need something of that: 

![image](https://user-images.githubusercontent.com/56369021/117844660-89ac5100-b288-11eb-924a-269610c2e1a7.png)

**Comment by Orange-hanter** [comment]
#313 
test
