### ISSUE TITLE
Client.Qt Refactoring

### ISSUE THREAD

**Issue by f1nal3** [f1nal3/Juniorgram#219]
1) Make sure code is written in accordance to our [code style](https://github.com/f1nal3/Juniorgram/wiki/Как-писать-код-на-CXX).
2) Try applying [const correctness](https://isocpp.org/wiki/faq/const-correctness)
3) Make sure everything has a name that has some meaning(try to get rid of int i = 0 for example)
4) Add some newlines if that helps separating the code logically.
5) OR even better: if a function does several things at once - consider splitting it into several functions for readability's sake.
6) Look through tests and try thinking about other test cases.

Feel free to use some refactoring guides such as: [this](https://betterprogramming.pub/the-art-of-refactoring-5-tips-to-write-better-code-3bc1f6f7689) and [this](https://dzone.com/articles/6-efficient-things-you-can-do-to-refactor-a-c-proj) or even [this](https://www.lattix.com/c-refactoring-tip-primitive-obsession/)

**Comment by StasDash** [comment]
I take Client.Qt/Style

**Comment by StasDash** [comment]
It seems like I took all refactoring
