### ISSUE TITLE
Library for YasSerialization

### ISSUE THREAD

**Issue by HRenata** [f1nal3/Juniorgram#225]
If we download yas from conan-center we have some warnings, that should be supressed.
We can solve this in different ways:
1) create a new package with fixed yas (there are some draft fixes [here](https://github.com/HRenata/yas)) in conan center
*maybe we need author's permission on it (I'm negotiating about this)
2) make yas as a part of project (e.g., folder 3rg party libs)
3) leave this as being...

**Comment by f1nal3** [comment]
No longer relevant.
