### ISSUE TITLE
Message box "Incorrect registration"

### ISSUE THREAD

**Issue by HRenata** [f1nal3/Juniorgram#231]
Create new windows that will be showed when user already exists/incorrect repeated password/etc (based on returned codes from RegistrationUnit::RegistrationCodes).
When client click on registration button, his entered data is being validated. We need inform him what is wrong with his entered data (login, email and password). Now informing takes place using the console, but it is not the best way. We need use some widgets for it.

**Comment by Orange-hanter** [comment]
Related with task #307
