### ISSUE TITLE
Look into a way to improve CMake targets structure

### ISSUE THREAD

**Issue by f1nal3** [f1nal3/Juniorgram#276]
It's quite messy at this point with various dependencies spreading around.

**Comment by f1nal3** [comment]
#404 is in the review state

**Comment by f1nal3** [comment]
As #404 is closed and since we've kinda sorted this I suggest we close this issue.
Also, during client decoupling we will resolve the rest of the issues.
@Orange-hanter

**Comment by Orange-hanter** [comment]
Agree
