### ISSUE TITLE
Profile server locally.

### ISSUE THREAD

**Issue by f1nal3** [f1nal3/Juniorgram#278]
Using VTune or something

**Comment by fisyamaloy** [comment]
We have only 1 connection to DB and it is opened during all server lifetime. It consumes extra resources, beacuse it never closes. We need some mechanism, which can help us don't waste this system resources when we don't need this connection to DB.

**Comment by fisyamaloy** [comment]
pqxx is not thread safe, but our server threads use only 1 connection to DB. The server is multithreaded. Operations are performed in a transaction, and if different threads push requests into one connection, then when you commit to the database, everything will be committed, when you rollback everything will be rolled back.
The better way - make connections for each server thread.

**Comment by fisyamaloy** [comment]
-PostgreRepository has 3 functions, which we can't test with DB-test. 
-Registration is in a separate module and not in ProstgreRepository. It is bad.
