### ISSUE TITLE
Loading behaviour

### ISSUE THREAD

**Issue by f1nal3** [f1nal3/Juniorgram#308]
As a Juniorgram user I want to see if something is happening in the background so that I know what is going on with the app.

For example, logging in might take some time, during which the controls should be locked and the cursor is changed to something cyclic.

**Comment by StasDash** [comment]
![image](https://user-images.githubusercontent.com/12201848/129058147-adcb248c-5cd7-45cb-b1bb-c55a8345045b.png)
