### ISSUE TITLE
Fix ChannelListWindow

### ISSUE THREAD

**Issue by GuskoMaksim** [f1nal3/Juniorgram#312]
The list of channels does not appear
![image](https://user-images.githubusercontent.com/57706182/126964013-89d5b493-195e-4a65-8f9d-1ed3380870d5.png)

The bug appeared after this commit
https://github.com/f1nal3/Juniorgram/commit/455d861bd24ddcf4523cee02c848e71c52622a5c

**Comment by StasDash** [comment]
It was before the commit

**Comment by GuskoMaksim** [comment]
I made a call with @Orange-hanter to analyze the bug.

The main error was found in PR number 297 (https://github.com/f1nal3/Juniorgram/pull/297).

The client was connected before creating windows and requests to the server, which led to this bug. It was also discovered that the request for channels was sent before we entered through the Login button.

To solve this problem, it was decided to correct the order of connecting the client and creating windows, the chat window will be created only after clicking the Login button.

**Comment by StasDash** [comment]
> The main error was found in PR number 297 (#297).
> 
> I made a call with @Orange-hanter to analyze the bug.
> 
> The client was connected before creating windows and requests to the server, which led to this bug. It was also discovered that the request for channels was sent before we entered through the Login button.
> 
> To solve this problem, it was decided to correct the order of connecting the client and creating windows, the chat window will be created only after clicking the Login button.

To solve the problem(channels on start)you need to remove, staticness of channellistwindow and create request system.
