### ISSUE TITLE
Fix Message Store

### ISSUE THREAD

**Issue by fisyamaloy** [f1nal3/Juniorgram#327]
1) We need to fix storing of messages in repository: message from user must be stored in appropriate tables of repository.
2) When user click "send", message must store in repository.
3) To follow the previous point, we need to know about channelID in where we send message, but client-side knows only about channels names.

**Comment by f1nal3** [comment]
Pls consider properly filling issues - I cannot comprehend what is wrong and what needs to be done. You can use "As a ... I want ... so that ..." template.

**Comment by fisyamaloy** [comment]
> Pls consider properly filling issues - I cannot comprehend what is wrong and what needs to be done. You can use "As a ... I want ... so that ..." template.

done
