### ISSUE TITLE
We need a way to improve our inheritance mechanism. 

### ISSUE THREAD

**Issue by glaush** [f1nal3/Juniorgram#347]
In this 

We have a [PostgreRepository](https://github.com/f1nal3/Juniorgram/blob/master/DataAccess/DataAccess.Postgre/PostgreRepository.hpp)  class that inherits from a base [IRepository](https://github.com/f1nal3/Juniorgram/blob/master/DataAccess/Public/Include/DataAccess/IRepository.hpp) class. Given this point, we have to override purely virtual functions in inherited classes and this is a problem. We need to find out how this is handled correctly.

**Comment by fisyamaloy** [comment]
Interface IRepository has too many functions. We can do many interfaces, which will have closely related functions (ISP principle). As a result we must realize only those interfaces, which we need in our class.

**Comment by vDrWool** [comment]
@Orange-hanter
Repos example: https://github.com/vDrWool/RepositoryExample/blob/master/RepositoryExample/GlobalRepository.h
Main: https://github.com/vDrWool/RepositoryExample/blob/master/RepositoryExample/main.cpp
