### ISSUE TITLE
Create issue template for pre-release activities

### ISSUE THREAD

**Issue by f1nal3** [f1nal3/Juniorgram#361]
Subtask of #357 

During release we need a set of tasks to do on the release branch. Tasks such as:
* Improving test coverage
* Improving doc coverage
* Manual testing
* Bug fixing
* Small adjustments if needed
* Can be expanded

Github offers issue templates that seem to fit the task perfectly. We need to investigate this and use those if possible for each release.

AC:
* issue template are created and can be used OR there is a strong point against using them.

**Comment by Orange-hanter** [comment]
The most interesting features are at beta conditions. But we can become testers and use those features.
@f1nal3 here the [link](https://github.com/features/issues)
