### ISSUE TITLE
Investigate whether we need to use alignment to send the header over the network. 

### ISSUE THREAD

**Issue by glaush** [f1nal3/Juniorgram#387]
Example: 

```cpp
#pragma pack( push, 1 )
	struct NetPubMHeader
	{
		uint16_t ProtocolVersion;
		NetPubMType MessageType;
		uint16_t Nonce;
		uint8_t IV[IVSize];
	};
#pragma pack( pop )
```

This section of the code uses an alignment mechanism. We need to investigate if it makes sense to introduce such a feature for our **MessageHeader**.

**Comment by Svidunovich** [comment]
Packed structures are slower than unpacked structures because not all processors support unaligned data access, but if we need the compiler not to insert empty data, this can be used, but how it will work must be checked on different compilers.
Do we need it?
