### ISSUE TITLE
Solve problems with SQL tables.

### ISSUE THREAD

**Issue by memorisecodead** [f1nal3/Juniorgram#568]
## Investigate and solve SQL table problems 
related to:
1.  message editing & message history recall request,
2.  message storage & response,
3.  message deletion,
4.  channel subscription & creating channel creation request.

**Comment by memorisecodead** [comment]
Part of the work I've already done, can I take over the assignment? @Orange-hanter

**Comment by Orange-hanter** [comment]
Your problem based on old version of SQL schema. 
**DO NOT USE SCHEMA ON WIKI**
