### ISSUE TITLE
Time conversion bug on server side

### ISSUE THREAD

**Issue by ivanboika** [f1nal3/Juniorgram#569]
![image](https://user-images.githubusercontent.com/63643593/173882163-4e46bc9c-a3d0-4ab1-8da8-db9fe98b5d4a.png)

I found it while writing tests on getMessageHistory method on server side (DataAccess.Postgre/PostgreRepositories.cpp)
It only produces when we have at least one message at our DB, if DB is empty -> everything is ok
Maybe it can crush our client, but I'm not quite sure about it

Expected behavior: 

SECTION("We've stored message, let's check our message history")
					{
						REQUIRE_FALSE(testMessageRepos.getMessageHistory(testChannelID).empty());
					}

The issue is conversion our time to uint64_t type:
![image](https://user-images.githubusercontent.com/63643593/173882580-d1accb66-2eee-4012-8dab-55544bf8f14e.png)
![image](https://user-images.githubusercontent.com/63643593/173882674-e8d7b8a7-1875-4797-8348-5a3d64a4f51b.png)

**Comment by memorisecodead** [comment]
If you look closely, it is a typical double number.  The way I see it, you should add a cast of double to the time on the string db.

**Comment by ivanboika** [comment]
I'll try right now

**Comment by ivanboika** [comment]
Yeah, it works
