### ISSUE TITLE
Update repository system - Explore FileRepository 

### ISSUE THREAD

**Issue by Orange-hanter** [f1nal3/Juniorgram#574]
## Parent Task: 
- https://github.com/f1nal3/Juniorgram/issues/401 

## Description:
Currently, we have a repository system, that perform unified interface for work with DB. One of the implementations is _FileRepository_.
Explore interface of _repository system_ and make a list of problems for finishing this module.

## Acceptance Criteria:
Readiness is determined by @Orange-hanter  after the presentation at the meeting.

**Comment by slavexx** [comment]
### Public/Include/DataAccess:

**_IRepository.hpp_** 

Don`t have detailed description next functions:

- _storeReply_
- _deleteMessage_

_**SQLStatements.hpp**_ needs to be divided into DML and DDL parts.

### DataAccess.Debug:

**_FileRepository.hpp_**

Implemented functions:

- _getAllChannelsList_
- _getMessageHistoryForUser_

Not implemented functions:

- _getReplyHistoryForUser_
- _storeMessage_
- _storeReply_
- _deleteMessage_
- _editMessage_
- _updateMessageReactions_
- _registerUser_
- _loginUser_

**_FileDB.hpp_** looks complete.

**_FileAdapter.hpp_** is not implemented.

**Comment by slavexx** [comment]
We have 'IRepository' class, which is not used on client/server sides. Only 'FileRepository' inherits it, but 'FileRepository' is not finished. With time 'IRepository' replaced by 'IMasterRepository', which used for client and server sides now. The 'IMasterRepository' have greater functionality, that 'IRepository' provides. Should 'IRepository' be removed?
@Orange-hanter
