### ISSUE TITLE
Fixing some details in PostgreRepositories.cpp

### ISSUE THREAD

**Issue by memorisecodead** [f1nal3/Juniorgram#575]
## Parent Task: 
#191 

## Description:
If we gonna start to work, we have some problems with process data in postgreRepositories.
This problem with lack "equal" value in one part of postgreRepositories. Also, we have some problems with Logger part, because in work proccess, we can see strange output.

**Comment by Orange-hanter** [comment]
@memorisecodead where description?

**Comment by memorisecodead** [comment]
> @memorisecodead where description?

Done it.
