### ISSUE TITLE
Improve logger

### ISSUE THREAD

**Issue by ivanboika** [f1nal3/Juniorgram#579]
### Our logger eats a part of information that we can see in the terminal. We need to fix this issue 
![image](https://user-images.githubusercontent.com/63643593/176486324-63f80e14-df2b-41f6-ad27-10892ed540db.png)
### We have back in future issue
![image](https://user-images.githubusercontent.com/63643593/177360006-b59c969d-ab57-4b25-a063-19d94ec98b58.png)

## Acceptance Criteria:
Logger shows us information in appropriate way, without eating parts of data

## Possible solutions:
I guess, we can find problem around threads. Maybe adding any mutex or something else will fix it. Or not
##How to produce:
You can start any type of tests (better DataAccess part) and you'll see in the terminal incorrect output
Also, we may launch client&server and check how logger shows us the output

**Comment by Orange-hanter** [comment]
Check out is compilation flags _-fsanitize=thread -fPIC_ are used. It could be useful in looking for a bug.
