### ISSUE TITLE
Fixing message's time sequence in logger

### ISSUE THREAD

**Issue by ivanboika** [f1nal3/Juniorgram#584]
## Parent Task: 
#579 was close to this issue, but not the same

## Description:
We have an issue with our time in logger output, sometimes we can see something like this. 
![image](https://user-images.githubusercontent.com/63643593/179785405-440d2ea3-6787-4b65-80a3-41c2eaf71f8d.png)

And that's not okey of course. However, the order of logger messages is right

## Acceptance Criteria:
We must have a right order (Fix of this task must not change that) and right sequence of messages in the meaning of timestamp

**Comment by memorisecodead** [comment]
I don't understand why it's not right?
In your example, which you cited, everything works correctly: first we kind of see the connection to the server, and then the server approves this connection or not. 
Where is the problem?

If the "problem" is time-related, then back to threads and thread processing. As I understand and see it, there are several threads running, and each message is constructed and output in the sequence in which they are designed. 
As I said above, we first accept, so to speak, "see the connection" and then "approve it or not".

The timing is correct, the functionality works in the sequence in which it was originally conceived.

**Comment by memorisecodead** [comment]
I have come to the conclusion that the messages are correct. There is no need to swap them. The time order needs to be modified.

**Comment by memorisecodead** [comment]
1: ![image](https://user-images.githubusercontent.com/70116007/183430544-ce7c084e-eea6-4255-b067-3404ab476d7b.png)
2: 
![image](https://user-images.githubusercontent.com/70116007/183431303-86021b02-9a05-4bab-b230-ec5255c74228.png)
3: 
![image](https://user-images.githubusercontent.com/70116007/183431397-a9a155fb-3f73-4bf0-adf0-ed55665ba6f4.png)
4:
![image](https://user-images.githubusercontent.com/70116007/183431467-c3f52968-d23f-4d8e-ad7a-90793111bf7f.png)
5: 
![image](https://user-images.githubusercontent.com/70116007/183431815-6609b35a-a9c5-48b7-b571-4a22cfa0a9ab.png)
6:
![image](https://user-images.githubusercontent.com/70116007/183432097-5a3cf10f-fcfc-4b98-b460-2a76ab4c7424.png)

**Comment by memorisecodead** [comment]
Only on two occasions, my timing was different.
It's definitely a bug.
