### ISSUE TITLE
Investigate Encryption/Compression

### ISSUE THREAD

**Issue by f1nal3** [f1nal3/Juniorgram#625]
tldr
Sec is good, compressed bytes go brrrrrr

**Comment by slavexx** [comment]
I planned to improve encryption of Juniorgram and use this task as my graduation project. Moreover, improving users' data security is required by Sonar for a long time, so i will make 2 good deals on 1. According to recommendations of Daniil, this task includes finding ways to encrypt data, which are located in canal client-server. Also there will be defined the method to identification.
