### ISSUE TITLE
Investigate a bug in the GCC Linux build.

### ISSUE THREAD

**Issue by memorisecodead** [f1nal3/Juniorgram#633]
## Problem:
GCC Linux Build is behaving strangely when running tests. It was noticed that when running Utility.Test, an error was thrown. 
Attached are some screenshots: 
![image](https://user-images.githubusercontent.com/70116007/215765682-411187af-a067-44ac-a6ee-b9258464725a.png)
![image](https://user-images.githubusercontent.com/70116007/215765710-d449fab8-9b52-4046-8815-fd3c61367150.png)
After the rebuild, this problem didn't occur. 
![image](https://user-images.githubusercontent.com/70116007/215765731-f7dfedc8-a662-46c3-8e25-bf725e880188.png)

## Description:
Find out what the problem is, and tell me why it happens.

**Comment by Orange-hanter** [comment]
any updates?

**Comment by f1nal3** [comment]
https://github.com/f1nal3/Juniorgram/actions/runs/4509951483/jobs/7940322282
this might be relevant?

**Comment by memorisecodead** [comment]
> this might be relevant?

sure

**Comment by memorisecodead** [comment]
Based on the thrown error, I assume that the method consoleLogTimestamp does not always work correctly, because in the attached screenshot(41 line), you can see that the time taken from the buffer (empty) is compared with the checked time. 

![image](https://user-images.githubusercontent.com/70116007/227742016-a41f8419-656e-4337-b67a-9f33801ffc43.png)

**Comment by memorisecodead** [comment]
By emulating this situation (by commenting out the consoleLogTimestamp method), I got the same result as in the previous screenshot.

![image](https://user-images.githubusercontent.com/70116007/227742110-af14c69f-59de-48ae-9558-68988e72fa5b.png)

**Comment by memorisecodead** [comment]
If you look at this screenshot, you can see that the time formatting is not correct.

https://user-images.githubusercontent.com/70116007/215765710-d449fab8-9b52-4046-8815-fd3c61367150.png
