### ISSUE TITLE
Add settings manager

### ISSUE THREAD

**Issue by f1nal3** [f1nal3/Juniorgram#84]
Wee need a way to change several settings values without compiling and deploying.
An example of this is the setup info for PostgreSQL database.

**Comment by f1nal3** [comment]
More example: user-defined font size and it's applications in Client.Qt

**Comment by f1nal3** [comment]
Since server and client.cli seem to not use(need) settings we've decided to use existing solutions for storing messages that is included with Qt.

**Comment by otratsiuk** [comment]
@StasDash I need a way to change few variables which are set in styles. Since StyleBasic.cpp is generated automatically I shouldn't change it. Could you please describe where in our code I may change e.g. font size?

**Comment by StasDash** [comment]
> @StasDash I need a way to change few variables which are set in styles. Since StyleBasic.cpp is generated automatically I shouldn't change it. Could you please describe where in our code I may change e.g. font size?

Right now I font isn't designed to change size on fly, try it on text or color
